# Generated by Django 4.2 on 2024-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/no-img.jpg', upload_to='Images/'),
        ),
    ]
